// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MusicCMS_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial class Album : IEntity
    {
        public Album()
        {
            ArtistAlbum = new HashSet<ArtistAlbum>();
            MusicAlbum = new HashSet<MusicAlbum>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdAlbum { get; set; }
        public string AlbumName { get; set; }
        public string ImageAlbum { get; set; }

        public virtual ICollection<ArtistAlbum> ArtistAlbum { get; set; }
        public virtual ICollection<MusicAlbum> MusicAlbum { get; set; }
    }
}