// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MusicCMS_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial class Artist : IEntity
    {
        public Artist()
        {
            ArtistAlbum = new HashSet<ArtistAlbum>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdArtist { get; set; }
        public string ArtistName { get; set; }
        public string ImageArtist { get; set; }

        public virtual ICollection<ArtistAlbum> ArtistAlbum { get; set; }
    }
}