// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MusicCMS_Entities.Concrete.DatabaseFirst;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial interface IMusicCMSContextProcedures
    {
        Task<List<PlaylistMusicStoredProcedureResult>> PlaylistMusicStoredProcedureAsync(int? pl, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
