// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MusicCMS_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial class MusicAlbum : IEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdMusicAlbum { get; set; }
        public int MusicId_forMusicAlbum { get; set; }
        public int AlbumId_forMusicAlbum { get; set; }

        public virtual Album AlbumId_forMusicAlbumNavigation { get; set; }
        public virtual Music MusicId_forMusicAlbumNavigation { get; set; }
    }
}