// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MusicCMS_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial class Music : IEntity
    {
        public Music()
        {
            MusicAlbum = new HashSet<MusicAlbum>();
            PlaylistMusic = new HashSet<PlaylistMusic>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdMusic { get; set; }
        public string MusicName { get; set; }
        public bool isPopularMusic { get; set; }
        public string ImageMusic { get; set; }
        public string MusicFile { get; set; }

        public virtual ICollection<MusicAlbum> MusicAlbum { get; set; }
        public virtual ICollection<PlaylistMusic> PlaylistMusic { get; set; }
    }
}