// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial class PlaylistMusicStoredProcedureResult
    {
        public string MusicName { get; set; }
        public string PlaylistName { get; set; }
    }
}
