// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MusicCMS_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial class PlaylistMusic : IEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdPlaylistMusic { get; set; }
        public int PlaylistId_forPlaylistMusic { get; set; }
        public int MusicId_forPlaylistMusic { get; set; }

        public virtual Music MusicId_forPlaylistMusicNavigation { get; set; }
        public virtual Playlist PlaylistId_forPlaylistMusicNavigation { get; set; }
    }
}