// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MusicCMS_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicCMS_Entities.Concrete.DatabaseFirst
{
    public partial class Playlist : IEntity
    {
        public Playlist()
        {
            PlaylistMusic = new HashSet<PlaylistMusic>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdPlaylist { get; set; }
        public string PlaylistName { get; set; }
        public string PlaylistDescription { get; set; }
        public string PlaylistDatetime { get; set; }
        public string ImagePlaylist { get; set; }
        public int UserAccountId_forPlaylist { get; set; }

        public virtual UserAccount UserAccountId_forPlaylistNavigation { get; set; }
        public virtual ICollection<PlaylistMusic> PlaylistMusic { get; set; }
    }
}