// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusicCMS.Models.Data
{
    public class Music
    {
        public Music()
        {
          
        }

        public int IdMusic { get; set; }
        public string MusicName { get; set; }
        public bool IsPopularMusic { get; set; }
        public string ImageMusic { get; set; }
        public string MusicFile { get; set; }


    }
}