// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusicCMS.Models.Data
{
    public class Radio
    {
        public int IdRadio { get; set; }
        public string RadioName { get; set; }
        public string ImageRadio { get; set; }
        public string RadioFile { get; set; }
        public string RadioDescription { get; set; }
        public string RadioCountry { get; set; }
    }
}